server:
  port: 50320
spring:
  datasource:
    url: jdbc:mysql:///app_wink_auth?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
